# اسم سير العمل
name: Build Python Application to EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install ttkbootstrap
          pip install matplotlib # <-- مكتبة الرسوم البيانية
          pip install Pillow     # <-- تابعة لمكتبة الرسوم البيانية

      - name: Build executable
        run: pyinstaller --onefile --windowed --name CardManagerUltimate --icon=NONE main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CardManager-Executable
          path: dist/CardManagerUltimate.exe
